openapi: 3.0.0

info:
  version: 1.0.0
  title: Profile service API
  contact:
    name: Dmitry Novikov
    email: dredfort.42@gmail.com
    url: "https://github.com/dredfort42"
  license:
    name: GNU General Public License v3.0
    url: "https://www.gnu.org/licenses/gpl-3.0.html"
  x-logo:
    url: "https://avatars.githubusercontent.com/u/102029973?v=4"
  description: |
    This is a description of the Profile service API and its operations.

tags:
  - name: User
    description: |
      The Profile user operations.
  - name: Device
    description: |
      The Profile device operations.

servers:
  - url: "http://localhost:4284"
    description: |
      Local server

paths:
  /api/v1/profile/user:
    post:
      tags:
        - User
      summary: Create a new user profile
      description: |
        Create a new user in the Profile service.
      security:
        - OAuth2AccessToken: []
      operationId: "UserCreate"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreate"
      responses:
        "201":
          description: |
            OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Profile created successfully"
                  profile:
                    $ref: "#/components/schemas/User"
        "400":
          description: |
            Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                missingToken:
                  summary: Missing token
                  value:
                    error: "invalid_request"
                    error_description: "Missing or invalid token"
                invalidJSON:
                  summary: Invalid JSON
                  value:
                    error: "invalid_request"
                    error_description: "Invalid request"
                missingFields:
                  summary: Missing required fields
                  value:
                    error: "invalid_request"
                    error_description: "Missing required fields"
        "409":
          description: |
            Profile already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                profileExists:
                  summary: Profile already exists
                  value:
                    error: "invalid_request"
                    error_description: "Profile already exists"
        "500":
          description: |
            Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                missingEmail:
                  summary: Missing email
                  value:
                    error: "invalid_request"
                    error_description: "Missing email"
                createUserError:
                  summary: Create user error
                  value:
                    error: "server_error"
                    error_description: "Error creating user profile"
    get:
      tags:
        - User
      summary: Get user profile
      description: |
        Get user profile from the Profile service.
      security:
        - OAuth2AccessToken: []
      operationId: "UserGet"
      responses:
        "200":
          description: |
            OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: |
            Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                missingToken:
                  summary: Missing token
                  value:
                    error: "invalid_request"
                    error_description: "Missing or invalid token"
        "404":
          description: |
            Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                missingProfile:
                  summary: Profile not found
                  value:
                    error: "not_found"
                    error_description: "Profile not found"
        "500":
          description: |
            Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                missingEmail:
                  summary: Missing email
                  value:
                    error: "invalid_request"
                    error_description: "Missing email"
                getUserError:
                  summary: Get user error
                  value:
                    error: "server_error"
                    error_description: "Error getting user profile"

    patch:
      tags:
        - User
      summary: Update user profile
      description: |
        Update user profile in the Profile service.
      security:
        - OAuth2AccessToken: []
      operationId: "UserUpdate"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreate"
      responses:
        "200":
          description: |
            OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Profile updated successfully"
                  profile:
                    $ref: "#/components/schemas/User"
        "400":
          description: |
            Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                missingToken:
                  summary: Missing token
                  value:
                    error: "invalid_request"
                    error_description: "Missing or invalid token"
                invalidJSON:
                  summary: Invalid JSON
                  value:
                    error: "invalid_request"
                    error_description: "Invalid request"
        "404":
          description: |
            Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                missingProfile:
                  summary: Profile not found
                  value:
                    error: "not_found"
                    error_description: "Profile not found"
        "500":
          description: |
            Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                missingEmail:
                  summary: Missing email
                  value:
                    error: "invalid_request"
                    error_description: "Missing email"
                getUserError:
                  summary: Get user error
                  value:
                    error: "server_error"
                    error_description: "Error getting user profile"
                updateUserError:
                  summary: Update user error
                  value:
                    error: "server_error"
                    error_description: "Error updating user profile"

    delete:
      tags:
        - User
      summary: Delete user profile
      description: |
        Delete user profile and all associated devices from the Profile service.
      security:
        - OAuth2AccessToken: []
      operationId: "UserDelete"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  $ref: "#/components/schemas/Email"
                password:
                  $ref: "#/components/schemas/Password"
      responses:
        "200":
          description: |
            OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User and profile deleted successfully"
        "400":
          description: |
            Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                missingToken:
                  summary: Missing token
                  value:
                    error: "invalid_request"
                    error_description: "Missing or invalid token"
                invalidJSON:
                  summary: Invalid JSON
                  value:
                    error: "invalid_request"
                    error_description: "Invalid request"
        "404":
          description: |
            Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                missingProfile:
                  summary: Profile not found
                  value:
                    error: "not_found"
                    error_description: "Profile not found"
        "500":
          description: |
            Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                missingEmail:
                  summary: Missing email
                  value:
                    error: "invalid_request"
                    error_description: "Missing email"
                errorGettingProfile:
                  summary: Error getting profile
                  value:
                    error: "server_error"
                    error_description: "Error getting user profile"
                errorCreatingDeleteRequest:
                  summary: Error creating delete user request
                  value:
                    error: "server_error"
                    error_description: "Error creating delete user request"
                errorSendingDeleteRequest:
                  summary: Error sending delete user request
                  value:
                    error: "server_error"
                    error_description: "Error sending delete user request"
                errorDeleteUser:
                  summary: Error deleting user
                  value:
                    error: "server_error"
                    error_description: "Error deleting user"
                deleteUserError:
                  summary: Delete user error
                  value:
                    error: "server_error"
                    error_description: "Error deleting user profile"

  /api/v1/profile/user/email:
    post:
      security:
        - OAuth2AccessToken: []
      tags:
        - User
      summary: Change a user's email
      description: |
        Change a user's email address in the Profile service.
      operationId: change_email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_email:
                  $ref: "#/components/schemas/Email"
                password:
                  $ref: "#/components/schemas/Password"
      responses:
        "200":
          description: |
            OK
          content:
            application/json:
              example:
                message: "Profile email changed successfully"
                email: new.email@example.com
        "400":
          description: |
            Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                missingToken:
                  summary: Missing token
                  value:
                    error: "invalid_request"
                    error_description: "Missing or invalid token"
                invalidJSON:
                  summary: Invalid JSON
                  value:
                    error: "invalid_request"
                    error_description: "Invalid request"
        "500":
          description: |
            Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                missingEmail:
                  summary: Missing email
                  value:
                    error: "invalid_request"
                    error_description: "Missing email"
                errorGettingProfile:
                  summary: Error getting profile
                  value:
                    error: "server_error"
                    error_description: "Error getting user profile"
                errorCreatingChangeEmailRequest:
                  summary: Error creating change email request
                  value:
                    error: "server_error"
                    error_description: "Error creating change email request"
                errorSendingChangeEmailRequest:
                  summary: Error sending change email request
                  value:
                    error: "server_error"
                    error_description: "Error sending change email request"
                errorChangeEmail:
                  summary: Error changing email
                  value:
                    error: "server_error"
                    error_description: "Error changing email"
                errorUpdatingEmail:
                  summary: Error updating user profile email in the database
                  value:
                    error: "server_error"
                    error_description: "Error updating user profile email in the database"

components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: access_token

  schemas:
    UserCreate:
      description: |
        |
        User profile creation request
      type: object
      properties:
        first_name:
          type: string
          example: "John"
        last_name:
          type: string
          example: "Smith"
        date_of_birth:
          type: string
          format: date # YYYY-MM-DD
        gender:
          type: string
          enum:
            - man
            - woman
            - other
      required:
        - first_name
        - last_name
        - date_of_birth

    Email:
      description: |
        |
        User email address
      type: string
      format: email
      example: john.smith@example.com

    Password:
      description: |
        |
        User password (base64 encoded)
      type: string
      format: password
      example: P@ssw0rd

    User:
      description: |
        |
        User profile
      allOf:
        - $ref: "#/components/schemas/UserCreate"
        - type: object
          properties:
            email:
              $ref: "#/components/schemas/Email"
          required:
            - email

    Error:
      description: |
        |
        Error response
      type: object
      properties:
        error:
          type: string
          example: "invalid_request"
        error_description:
          type: string
          example: Missing required fields
